### ISSUE TITLE
Autostart lacking, iso is bare bones

### ISSUE THREAD

**Issue by adityatr64** [acmpesuecc/nycto-os#1]
Make a bash script to enable and run 

- firewalld
- NetworkManager
- sddm
- bluetooth
- cups

run locale-gen in the same script

In profiledef.sh

- Add the script with appropriate permissions into profiledef.sh
- Add polkit-1 and sudoers.d with appropriate permissions

**Comment by Coologtvil** [comment]
can i work on this?

**Comment by adityatr64** [comment]
!assign @Coologtvil 60

**Comment by adityatr64** [comment]
!deassign

**Comment by adityatr64** [comment]
!assign @Coologtvil 60

**Comment by adityatr64** [comment]
Do Not Use .bashrc to autorun

**Comment by adityatr64** [comment]
!deassign
