### ISSUE TITLE
Make kitty default terminal

### ISSUE THREAD

**Issue by adityatr64** [acmpesuecc/nycto-os#3]
The KDE default terminal(Konsole) doesnt match the aethetic of the distro

- Make kitty as default terminal
- change wallpaper to this https://github.com/laggy-tux/tokyo-night-openbox/blob/main/wall-01.png
- make sure the configs are taken from https://github.com/adityatr64/dotfiles

This can be achieved either via a autorun script or through kde conf files  
if script file is used make sure to add them to profiledef premissions and auto run it on boot

**Comment by RisuKumari11** [comment]
can i get assigned this

**Comment by adityatr64** [comment]
!assign @RisuKumari11 75

**Comment by RisuKumari11** [comment]
going for dinner give me time

**Comment by adityatr64** [comment]
!extend 25

**Comment by RisuKumari11** [comment]
cant solve

**Comment by adityatr64** [comment]
Do want to me to deassign?

**Comment by adityatr64** [comment]
!deassign

**Comment by RahulBiju-dev** [comment]
Please Assign

**Comment by adityatr64** [comment]
!assign @RecklessSoftwareGuy 45

**Comment by adityatr64** [comment]
!deassign
